### ISSUE TITLE
Training data set

### ISSUE THREAD

**Issue by jianjun0407** [arcadelab/FastSAM3D#2]
Thank you for sharing. Could you introduce the training data set used in FastSAM3D model training?

**Comment by skill-diver** [comment]
We have list it in the expirement part of the paper, pls check, thank you.

**Comment by jianjun0407** [comment]
Indeed, I saw the data set introduction about validation in the paper, but I did not see the data set introduction about train. I will review the paper again later, thank you for your reply

**Comment by skill-diver** [comment]
We mainly use Brats2021, AMOS, and Totalsegmentator to train.

**Comment by joseph-bae** [comment]
For BRATS, which modalities do you use? Do you combine all modalities into a single image (4 channels?) Or do you instead treat each modality as a separate sample?

**Comment by skill-diver** [comment]
We combine them.
