### ISSUE TITLE
Messy Dependencies

### ISSUE THREAD

**Issue by joseph-bae** [arcadelab/FastSAM3D#3]
Hello, I appreciate the release of the code, but am having trouble installing the required packages from the requirements file. It seems likely that many of these requirements are unnecessary to run the code, and in some cases there are conflicting dependencies (e.g. the file calls for a specific version of numpy, but other packages are incompatible with that version of numpy). Is there any possibility of updating the requirements file with only the necessary packages and/or versions?

Thank you.

**Comment by skill-diver** [comment]
I fixed the requirements.txt. If you still have problems when you run the code, you can install only those packages that dependency error prompts you to install.
